/// Flutter icons Bcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bcons
///      fonts:
///       - asset: fonts/Bcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Bcons {
  Bcons._();

  static const _kFontFam = 'Bcons';

  static const IconData height = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData weight = const IconData(0xe801, fontFamily: _kFontFam);
}
